# Generated by Django 2.2.12 on 2020-07-08 01:18

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Paciente', models.CharField(max_length=50, null=True)),
                ('Apellido_Paterno', models.CharField(max_length=100)),
                ('Apellido_Materno', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=50)),
                ('Fecha_Nacimiento', models.DateField(blank=True, default='01/01/2000', null=True)),
                ('Edad', models.PositiveSmallIntegerField(default='0', null=True)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('Estado_Civil', models.CharField(blank=True, max_length=30, null=True)),
                ('Ocupacion', models.CharField(blank=True, max_length=30, null=True)),
                ('Nacionalidad', models.CharField(blank=True, max_length=30, null=True)),
                ('Domicilio', models.TextField(blank=True, max_length=200, null=True)),
                ('Ciudad', models.CharField(blank=True, default='CDMX', max_length=30, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_record', models.CharField(max_length=50, null=True)),
                ('Expediente', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Signos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BMI', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Altura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Peso', models.IntegerField()),
                ('Temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('Frecuencia_Cardiaca', models.CharField(blank=True, max_length=10, null=True)),
                ('Presion', models.CharField(blank=True, max_length=10, null=True)),
                ('id_Expediente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_Expediente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Record'),
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('Fecha_galeria_creada', models.DateField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paciente.Paciente')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Consulta', models.CharField(max_length=20)),
                ('Fecha_consulta_creada', models.DateField(auto_now_add=True)),
                ('Fecha_consulta_modificada', models.DateField(auto_now=True)),
                ('Motivo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Diagnostico', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('id_Expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Antecedentes_Patologicos', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Antecedentes_Hereditarios', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Antecedentes_Quirurgicos', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Alergias', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Medicamentos', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('id_Expediente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('notas', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='files')),
                ('file_2', models.FileField(blank=True, null=True, upload_to='files')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('galeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.Galeria')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
